export const ROUTES = {
  DEFAULT: "/",
  SAMPLE_PAGE: "sample-page",
  CREATE_EMPLOYEE: "create-employee",
  CREATE_DESIGNATION: "create-designation",
  CREATE_EMPLOYEE_ADD: "create-employee-add",
  CREATE_SHIFT: "create-shift",
  CREATE_DEDUCTION: "create-deduction",
  CREATE_LEAVE_CATEGORY: "create-leave-category",
  CREATE_COMPANY: "create-company",
  CREATE_FINANCIAL_YEAR: "create-financial-year",
  CREATE_DEPARTMENT: "create-department",
  CREATE_HOLIDAY: "create-hoiliday",
  CREATE_EMPLOYEE_EXCEL: "create-employee-excel",
  SETTINGS_PAYROLL_GRADE: "settings-payroll-grade",
  SETTINGS_PAYROLL_ADDITION: "settings-payroll-addition",
  SETTINGS_PAYROLL_DEDUCTION: "settings-payroll-deduction",
  CONFIGURE_PAYROLL_GRADE: "configure-payroll-grade",
  SALARY_PROCESS_PAYROLL: "salary-process-payroll",
  EMPLOYEE_LIST: "employee-list",
  EMPLOYEE_INFORMATION: "employee-information"
};
