export const ROUTES = {
  DEFAULT: "/",
  SAMPLE_PAGE: "sample-page",
  CREATE_EMPLOYEE: "create-employee",
  CREATE_DESIGNATION: "create-designation",
  CREATE_EMPLOYEE_ADD: "create-employee-add",
  CREATE_SHIFT: "create-shift",
  CREATE_LEAVE_CATEGORY: "create-leave-category",
  CREATE_LEAVE_CONFIG: "create-leave-config",
  CREATE_DEDUCTION: "create-deduction",
  CREATE_COMPANY: "create-company",
  UPDATE_COMPANY: "update-company",
  CREATE_FINANCIAL_YEAR: "create-financial-year",
  CREATE_DEPARTMENT: "create-department",
  CREATE_HOLIDAY: "create-hoiliday",
  CREATE_EMPLOYEE_EXCEL: "create-employee-excel",
  SETTINGS_PAYROLL_GRADE: "settings-payroll-grade",
  SETTINGS_PAYROLL_ADDITION: "settings-payroll-addition",
  SETTINGS_PAYROLL_DEDUCTION: "settings-payroll-deduction",
  CONFIGURE_PAYROLL_GRADE: "configure-payroll-grade",
  CONFIGURE_EMPLOYEE_GRADE: "configure-employee-grade",
  SALARY_PROCESS_PAYROLL: "salary-process-payroll",
  SALARY_PROCESS_LIST: "salary-process-list",
  EMPLOYEE_LIST: "employee-list",
  EMPLOYEE_INFORMATION: "employee-information",
  LEAVE_ASSIGN: "leave-assign",
  EMPLOYEE_ATTENDANCE_CONFIG:"employee-attemdance-config",
  TAKE_ATTENDANCE:"take-attendantance",
  UPDATE_ATTENDANCE:"update-attendantance",
  BANK_ADVISE_CONTENT:"bank-advise-content",
};
