export const ROUTES = {
  DEFAULT: "/",
  SAMPLE_PAGE: "sample-page",
  CREATE_EMPLOYEE: "create-employee",
  CREATE_DESIGNATION: "create-designation",
  CREATE_EMPLOYEE_ADD: "create-employee-add",
  CREATE_SHIFT: "create-shift",
  CREATE_LEAVE_CATEGORY: "create-leave-category",
  CREATE_LEAVE_CONFIG: "create-leave-config",
  CREATE_DEDUCTION: "create-deduction",
  CREATE_COMPANY: "create-company",
  UPDATE_COMPANY: "update-company",
  CREATE_FINANCIAL_YEAR: "create-financial-year",
  CREATE_DEPARTMENT: "create-department",
  CREATE_HOLIDAY: "create-hoiliday",
  CREATE_EMPLOYEE_EXCEL: "create-employee-excel",
  SETTINGS_PAYROLL_GRADE: "settings-payroll-grade",
  SETTINGS_PAYROLL_ADDITION: "settings-payroll-addition",
  SETTINGS_PAYROLL_DEDUCTION: "settings-payroll-deduction",
  CONFIGURE_PAYROLL_GRADE: "configure-payroll-grade",
  CONFIGURE_EMPLOYEE_GRADE: "configure-employee-grade",
  SALARY_PROCESS_PAYROLL: "salary-process-payroll",
  SALARY_PROCESS_LIST: "salary-process-list",
  SALARY_SLIP: "salary-slip",
  EMPLOYEE_LIST: "employee-list",
  EMPLOYEE_ASSIGN_DESIGNATION: "employee-assign-designation",
  EMPLOYEE_BANK_INFO: "employee-bank-info",
  EMPLOYEE_INFORMATION: "employee-information",
  LEAVE_ASSIGN: "leave-assign",
  LEAVE_PENDING: "leave-pending",
  EMPLOYEE_ATTENDANCE_CONFIG:"employee-attemdance-config",
  TAKE_ATTENDANCE:"take-attendantance",
  UPDATE_ATTENDANCE:"update-attendantance",
  BANK_ADVISE_CONTENT:"bank-advise-content",
  BANK_ADVISE_VIEW:"bank-advise-view",
  DEVICE_PROCESS:"device-process",
  ID_MAPPING:"id-mapping",
  HOLIDAY: "holiday",
  HR_REPORT_DATE_WISE: "hr-report-date-wise",
  HR_REPORT_MONTH_WISE: "hr-report-month-wise",
  APPLY_LEAVE: "apply-leave",
  EOMPLOYEE_ATACHEMENTS: "employee-atachmenmts",
  EOMPLOYEE_ATTENDNACE: "employee-attendance",
  EOMPLOYEE_REMARKS: "employee-remarks",
  USER_LIST: "user-list",
};
